Update nodejs_npm_build_analysis.yml
Added an analysis file

Signed-off-by: Stephen Crocker <92754842+stevecrocker@users.noreply.github.com>

diff --git a/.github/workflows/nodejs_npm_build_analysis.yml b/.github/workflows/nodejs_npm_build_analysis.yml
--- a/.github/workflows/nodejs_npm_build_analysis.yml
+++ b/.github/workflows/nodejs_npm_build_analysis.yml
@@ -1,1 +1,108 @@
 
+name: Build Verification of Node.JS project
+
+on:
+  workflow_call:
+    secrets:
+      SCM_USER:
+        required: true
+      SCM_TOKEN:
+        required: true
+      SONAR_TOKEN:
+        required: true
+
+permissions:
+  contents: read
+  actions: read
+  checks: write
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4.1.7
+        with:
+          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
+      - name: Set up Node.JS 22.x
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22.x
+      - name: Find yarn cache
+        id: yarn-cache-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: ${{ steps.yarn-cache-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+
+      - name: Setup Pallas Scoped Github package repository
+        run: echo "@pallassystems:registry=https://npm.pkg.github.com/" >> ~/.npmrc
+
+      - name: Add authentication for scoped package repository
+        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.SCM_TOKEN }}" >> ~/.npmrc
+
+      - name: Add normal registry
+        run: echo "registry=https://registry.npmjs.org" >> ~/.npmrc
+
+      - name: Run NPM Install
+        run: npm ci
+
+      - name: Run NPM Test
+        run: npm run test -- --coverage
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1.9.1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: JEST Tests # Name of the check run which will be created
+          path: junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
+
+      - name: Save Code Linting Report JSON
+        run: npm run lint --if-present
+        continue-on-error: true
+
+      - name: ESLint Annotate from Report JSON
+        uses: ataylorme/eslint-annotate-action@3.0.0
+        with:
+          report-json: "eslint_report.json"
+
+      - name: Upload ESLint report
+        uses: actions/upload-artifact@v4
+        with:
+          name: eslint_report.json
+          path: eslint_report.json
+
+      - name: Upload StyleLint report
+        uses: actions/upload-artifact@v4
+        with:
+          name: stylelint_report.json
+          path: stylelint_report.json
+
+      - name: Prep ESLint files for sonar
+        if: ${{ hashFiles('eslint_report.json') != '' }}
+        run: |
+          sed -i 's|${{ github.workspace }}/||g' eslint_report.json
+
+      - name: Prep Style files for sonar
+        if: ${{ hashFiles('stylelint_report.json') != '' }}
+        run: |
+          sed -i 's|${{ github.workspace }}/||g' stylelint_report.json
+
+      - name: Test for lcov
+        if: ${{ hashFiles('./coverage/lcov.info') == '' }}
+        run: |
+          npm run test -- --coverage
+          cat ./coverage/lcov.info
+
+      # Automatic Scanner is enabled
+      - name: SonarCloud Analysis
+        uses: SonarSource/sonarcloud-github-action@master
+        env:
+          GITHUB_USER: ${{ secrets.SCM_USER }}
+          GITHUB_TOKEN: ${{ secrets.SCM_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
